spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  datasource:
    url: jdbc:mysql:///seller?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql:true
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
logging:
  level:
    com.googlecode.jsonrpc4j: debug
server:
  servlet:
    context-path: /seller
  port: 8092
rpc:
  client:
    url: http://localhost:8091/manager/
    basePackage: com.imooc.api
swagger:
  groupName: seller
  basePackage: com.imooc.seller.controller
  title: 销售端API
  description: >
    authId 是由本方提供给接口调用方用于安全控制及身份识别，请在需要此参数的接口上，通过请求头传递。
    sign 是接口调用方使用私钥对请求对象中的非空字段按字典排序之后的JSON字符串进行的签名。请在需要此参数的接口上，通过请求头传递。

