spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql:true
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true
server:
  context-path: /manager
  port: 8091
swagger:
  groupName: manager
  basePackage: com.imooc.manager.controller